config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  'about' => 'static_pages#about'
  get  'contact' => 'static_pages#contact'

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#if no page title provided, show base title instead
	def full_title(page_title='')
		base_title= "J TREEZ"
		if page_title.empty?
			base_title
		else
			"#{base_title}||#{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		JEAH
	</small>
	<nav>
		<ul>
			<li><%= link_to "ABOUT", about_path %> </li>
			<li><%= link_to "CONTACT", contact_path %> </li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class='container'>
	<%= link_to "J TREEZ", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "HOME", root_path %></li>
				<li><%= link_to "ABOUT", about_path %></li>
				<li><%= link_to "CONTACT", contact_path %></li>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  	</script>
  <![end if]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <!--<%= debug(params) if Rails.env.development? %>-->
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "ABOUT") %>
<h1>ABOUT</h1>
<p>
ABOUT
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "CONTACT") %>
<h1>CONTACT</h1>
<p>
CONTACT
</p>

app/views/static_pages/home.html.erb
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>
<BR>